#!/system/bin/sh
# service.sh — KSU/Magisk/Apatch 兼容入口 + 看门狗 v0.3(死因记录)
MODDIR=$(dirname "$0")
BB=""
for c in /data/adb/ksu/bin/busybox /data/adb/magisk/busybox /data/adb/ap/bin/busybox; do
  [ -x "$c" ] && { BB=$c; break; }
done
export STATS_LOG="$MODDIR/data/stats.log"; mkdir -p "$MODDIR/data"
[ -n "$BB" ] && export ASH_STANDALONE=1
run() { [ -n "$BB" ] && "$BB" ash "$@" || sh "$@"; }

# --- COSGuard bridge (stage2): 配置桥入 + 遥测桥出 ---
. "$MODDIR/engine/lists.sh" 2>/dev/null || true
BRIDGE_DIR=/data/system/cosmem
BRIDGE=$BRIDGE_DIR/guard.conf
TELEM=$BRIDGE_DIR/guard.telemetry

guard_bridge() {
  mkdir -p "$BRIDGE_DIR" 2>/dev/null
  chown system:system "$BRIDGE_DIR" 2>/dev/null
  chmod 775 "$BRIDGE_DIR" 2>/dev/null
  local jc="$MODDIR/config/memory.json" mode="" block="" fze="" fzline=""
  if [ -f "$jc" ]; then
    mode=$(sed -n 's/.*"mode" *: *"\([^"]*\)".*/\1/p' "$jc" | head -1)   # guard 是 memory.json 唯一 mode 键
    block=$(sed -n 's/.*"block_rules" *: *"\([^"]*\)".*/\1/p' "$jc" | head -1)
    fzline=$(sed -n "/"freeze"/,/}/p" "$jc" | grep "enabled" | head -1)
  fi
  case "$fzline" in *true*) fze=1;; *) fze=0;; esac
  [ "$mode" = guard ] || mode=observe
  [ -n "$block" ] || block=o-stop,frozen,cached,empty,cpu
  eval "$(parse_lists "${LIST_PATH:-/sdcard/Android/COSMemory/名单列表.conf}" 2>/dev/null)"
  {
    echo "# COSGuard bridge - generated by COSMemory service.sh"
    echo "VERSION=1"
    echo "MODE=$mode"
    echo "BLOCK=$block"
    for p in $WHITE_LIST; do echo "WHITE $p"; done
    # FREEZE 桥即状态 (spec §4.2): 开关开且名单非空才出行, 否则 hook/引擎双静默
    if [ "$fze" = 1 ] && [ -n "$FREEZE_LIST" ]; then
      echo "FREEZE_ENABLED=1"
      for p in $FREEZE_LIST; do echo "FREEZE $p"; done
    fi
  } > "$BRIDGE.tmp" 2>/dev/null && mv -f "$BRIDGE.tmp" "$BRIDGE" 2>/dev/null \
    && chmod 644 "$BRIDGE" && chown system:system "$BRIDGE"
}

guard_harvest() {
  [ -f "$TELEM" ] || return 0
  mkdir -p "$MODDIR/data/guard" 2>/dev/null || return 0
  cat "$TELEM" >> "$MODDIR/data/guard/$(date +%F).log" 2>/dev/null && : > "$TELEM"
}

while [ "$(getprop sys.boot_completed)" != "1" ]; do sleep 5; done
sleep 3
while :; do
  if ! pgrep -f 'engine/memory.sh' >/dev/null 2>&1; then
    PA=unknown
    if [ -f "$MODDIR/data/engine.started" ]; then
      ST=$(cat "$MODDIR/data/engine.started" 2>/dev/null)
      [ -n "$ST" ] && PA="$(( $(date +%s) - ST ))s"
      rm -f "$MODDIR/data/engine.started"
    fi
    echo "[$(date '+%F %T')] WATCHDOG restart prev_alive=$PA" >> "$STATS_LOG"
    WORKDIR="$MODDIR/data" STATS_LOG="$STATS_LOG" run "$MODDIR/engine/memory.sh" >/dev/null 2>&1 &
  fi
  guard_bridge
  guard_harvest
  sleep 30
done
