#!/system/bin/sh
# engine/bridge.sh — guard_bridge 抽取 (自 service.sh, DRY: service/listedit 双 source)
# 依赖环境: MODDIR, BRIDGE_DIR, BRIDGE, parse_lists (engine/lists.sh 由调用方 source)
guard_bridge() {
  mkdir -p "$BRIDGE_DIR" 2>/dev/null
  chown system:system "$BRIDGE_DIR" 2>/dev/null
  chmod 775 "$BRIDGE_DIR" 2>/dev/null
  local jc="$MODDIR/config/memory.json" mode="" block="" fze="" fzline=""
  if [ -f "$jc" ]; then
    mode=$(sed -n 's/.*"mode" *: *"\([^"]*\)".*/\1/p' "$jc" | head -1)   # guard 是 memory.json 唯一 mode 键
    block=$(sed -n 's/.*"block_rules" *: *"\([^"]*\)".*/\1/p' "$jc" | head -1)
    fzline=$(sed -n "/"freeze"/,/}/p" "$jc" | grep "enabled" | head -1)
  fi
  case "$fzline" in *true*) fze=1;; *) fze=0;; esac
  [ "$mode" = guard ] || mode=observe
  [ -n "$block" ] || block=o-stop,frozen,cached,empty,cpu,athena
  # 名单暂不可读(开机 /sdcard FUSE 晚于 boot_completed 就绪)时保留旧桥不覆盖 —
  # 否则会写出无 WHITE 行的桥 → COSGuard no-white 降级 (2026-10-05 根因修复)
  load_lists "${LIST_PATH:-/sdcard/Android/COSMemory/名单列表.conf}" || return 1
  {
    echo "# COSGuard bridge - generated by COSMemory service.sh"
    echo "VERSION=1"
    echo "MODE=$mode"
    echo "BLOCK=$block"
    for p in $WHITE_LIST; do echo "WHITE $p"; done
    # FREEZE 桥即状态 (spec §4.2): 开关开且名单非空才出行, 否则 hook/引擎双静默
    if [ "$fze" = 1 ] && [ -n "$FREEZE_LIST" ]; then
      echo "FREEZE_ENABLED=1"
      for p in $FREEZE_LIST; do echo "FREEZE $p"; done
    fi
  } > "$BRIDGE.tmp" 2>/dev/null && mv -f "$BRIDGE.tmp" "$BRIDGE" 2>/dev/null \
    && chmod 644 "$BRIDGE" && chown system:system "$BRIDGE"
}
